### ISSUE TITLE
TypeError: Cannot read property 'equals' of null

### ISSUE THREAD

**Issue by ZR2** [SteamingMutt/WildBeast#27]
```
info: Executing <!purge 1> from Josh (ZR2)
/home/divbot/node_modules/discord.js/lib/Structures/ServerChannel.js:53
                        if (this.server.owner.equals(user)) {
                                             ^

TypeError: Cannot read property 'equals' of null
    at TextChannel.permissionsOf (/home/divbot/node_modules/discord.js/lib/Struc                                                                                                 tures/ServerChannel.js:53:25)
    at Object.Commands.purge.fn (/home/divbot/runtime/commands.js:381:22)
    at /home/divbot/DougBot.js:193:33
    at Object.exports.GetLevel (/home/divbot/runtime/permissions.js:9:12)
    at Client.<anonymous> (/home/divbot/DougBot.js:174:21)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (/home/divbot/node_modules/discord.js/lib/C                                                                                                 lient/InternalClient.js:1365:16)
    at WebSocket.onMessage (/home/divbot/node_modules/ws/lib/WebSocket.js:418:14                                                                                                 )
    at emitTwo (events.js:87:13)

```

**Comment by ZR2** [comment]
abalabahaha fixed this ;)
